name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core 3.1.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
